name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
